<a href="https://colab.research.google.com/github/YohansHailu/a2sv_ml_track/blob/main/Checkpoints.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Checkpoints

**CP1**:
Given the list $[A, B, C]$, use the `itertools` module to generate all possible
combinations of 2 elements.

**Expected Output**:
$$
 (A, B) \\
 (A, C) \\
 (B, C)
$$

In [4]:
#your code here
import itertools
arr = ["A","B","C","D"]
combos = []
for val in itertools.combinations(arr,2):
  combos.append(val)

combos

[('A', 'B'), ('A', 'C'), ('A', 'D'), ('B', 'C'), ('B', 'D'), ('C', 'D')]

**CP2**:
Use the `itertools` module to create a sequence that cycles through
['Python', 'is', 'fun'] infinitely. Print the first 10 elements of the sequence.

**Expected Output**:
$$
Python \\
is\\
fun\\
Python\\
is\\
fun\\
Python\\
is\\
fun\\
Python
$$

In [9]:
#your code here
str_arr = ['Python', 'is', 'fun']
str_arr_inf = itertools.cycle(str_arr)
for i in range(12):
  print(next(str_arr_inf))

Python
is
fun
Python
is
fun
Python
is
fun
Python
is
fun


**CP3**:
Use the `glob` module to list all python (.py) files in your current working directory.




In [22]:
#your code here
# just testing here
import os
print(os.getcwd())
print(os.listdir())


import glob
test_ = glob.glob('*.csv',root_dir="./sample_data", recursive=True)
print(test_)

glob.glob('*.py')

/content
['.config', 'sample_data']
None
['mnist_train_small.csv', 'mnist_test.csv', 'california_housing_test.csv', 'california_housing_train.csv']


[]

**CP4**: You are given the following HTML content below. Write a function that uses BeautifulSoup to parse the HTML and extract the text inside the   '$<p>$'   tag.


In [ ]:
#<html><body><div class='main'><h1>Welcome to AI</h1><p>AI is transforming the world</p></div></body></html>

In [30]:
#your code here
page = "<html><body><div class='main'><h1>Welcome to AI</h1><p>AI is transforming the world</p></div></body></html>"
from bs4 import BeautifulSoup as bs
soup = bs(page)
#print(soup.prettify())

text = soup.p.string
print(text)

print(soup("p")[0].string)

AI is transforming the world
AI is transforming the world


**CP5**: Write a function that uses the re module to replace all occurrences of the word "AI" with "Artificial Intelligence" in a given text.

In [34]:
#your code here
test_str = "AI for a long time AI. Has been through.AI this AcI, blah blah AI.AI"
import re
res = re.findall("AI", test_str)
print(res)


long_str = re.sub("AI","Artificial Intelligence", test_str )
long_str

['AI', 'AI', 'AI', 'AI', 'AI']


'Artificial Intelligence for a long time Artificial Intelligence. Has been through.Artificial Intelligence this AcI, blah blah Artificial Intelligence.Artificial Intelligence'

**CP6**: Create a numpy array of 10 zeros.

In [38]:
#your code here
import numpy as np
ten_zeros = np.zeros(10, dtype="int")
print(ten_zeros)

ten_zeros = np.arange(10, dtype="int") * 0
ten_zeros

[0 0 0 0 0 0 0 0 0 0]


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

**CP7** Create a numpy array of the integers from 10 to 49.

In [39]:
#your code here
r_nums = np.arange(10, 49)
r_nums

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48])

**CP8**: Create a 3x3 numpy matrix, filled with values ranging from 0 to 8.

In [43]:
#your code here
eight_mat = np.random.random((3,3)) * 8
eight_mat

array([[1.12743631, 3.6146836 , 1.84284513],
       [4.29872796, 5.32052381, 1.56455794],
       [0.81027525, 2.5884969 , 2.54621363]])

**CP9**: Explain why machine learning models require large amounts of data? What does it mean for an amount of data to be **large**?

In [45]:
#Models are designed to learn from data, but they can only be as smart as the information they're given.
#Even the most sophisticated models won't be able to perform well if they're trained on a small amount of data.

**CP10**: Explain 2 ways AI can be used in an adverserial way, and what can be done to prevent it.

In [50]:
#1 If the data used to train an AI model is skewed or incomplete, it may not be able to make fair or accurate predictions for certail groups.
#2 If we ever reach a stage of true artificial general intelligence (AGI), these machines may not care about us humans.
#3 The rise of powerful AI in certain countries has potential implications for global power dynamics.